// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import { Document } from '@contentful/rich-text-types'

export interface IButtonFields {
  /** Title */
  title: string

  /** Button Text */
  text: string

  /** Button Link */
  href: string

  /** Color */
  color?: 'default' | 'primary' | 'secondary' | undefined

  /** Variant */
  variant?: 'text' | 'outlined' | 'contained' | undefined
}

/** A Button to embed in another piece of text */

export interface IButton extends Entry<IButtonFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'button'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IColumnListFields {
  /** Title */
  title: string

  /** Body */
  body: Document
}

/** A list of items that should wrap to a certain number of columns. Should only have a list in the content. */

export interface IColumnList extends Entry<IColumnListFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'columnList'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IContactFormFields {
  /** Title */
  title: string
}

export interface IContactForm extends Entry<IContactFormFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'contactForm'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IContentBlockFields {
  /** Title */
  title: string

  /** Body */
  body?: Document | undefined

  /** Background Image */
  backgroundImage?: Asset | undefined

  /** Background Color */
  backgroundColor?: string | undefined

  /** Featured Image */
  featuredImage?: Asset | undefined

  /** Text Color */
  textColor?: string | undefined

  /** Theme */
  theme?: 'default' | 'hero' | undefined

  /** Height */
  height?: number | undefined

  /** Text Align */
  textAlign?: 'left' | 'center' | 'right' | 'justify' | undefined
}

/** A full-width block that can be placed into content (e.g. on the Home page) */

export interface IContentBlock extends Entry<IContentBlockFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'contentBlock'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IGridContainerFields {
  /** Title */
  title: string

  /** Grid Items */
  gridItems: IGridItem[]

  /** Align Items */
  alignItems?:
    | 'flex-start'
    | 'center'
    | 'flex-end'
    | 'stretch'
    | 'baseline'
    | undefined

  /** Justify */
  justify?:
    | 'flex-start'
    | 'center'
    | 'flex-end'
    | 'space-between'
    | 'space-around'
    | 'space-evenly'
    | undefined

  /** Text Align */
  textAlign?: 'left' | 'center' | 'right' | 'justify' | undefined
}

export interface IGridContainer extends Entry<IGridContainerFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'gridContainer'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IGridItemFields {
  /** Title */
  title: string

  /** Content */
  body: Document

  /** xs */
  xs?: number | undefined

  /** sm */
  sm?: number | undefined

  /** md */
  md?: number | undefined

  /** lg */
  lg?: number | undefined
}

export interface IGridItem extends Entry<IGridItemFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'gridItem'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ILinkFields {
  /** Title */
  title: string

  /** Short Title */
  shortTitle?: string | undefined

  /** Link URL/URI */
  uri: string
}

/** A link to content on the internet, or an internal link to a page on this site (e.g. an automatically-generated page, like a collection) */

export interface ILink extends Entry<ILinkFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'link'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IPageFields {
  /** Title */
  title: string

  /** Short Title */
  shortTitle?: string | undefined

  /** Slug */
  slug: string

  /** Body */
  body?: Document | undefined

  /** Featured Image */
  featuredImage?: Asset | undefined

  /** Banner Image */
  bannerImage?: Asset | undefined

  /** Hero Image */
  heroImage?: Asset | undefined

  /** Containment */
  containment?: 'default' | 'full-width' | undefined
}

/** A basic web page */

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'page'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IPictureLinkFields {
  /** Title */
  title: string

  /** Body */
  body?: Document | undefined

  /** Featured Image */
  featuredImage: Asset

  /** Link */
  link: IPage | IPost
}

export interface IPictureLink extends Entry<IPictureLinkFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'pictureLink'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IPictureLinkGroupFields {
  /** Title */
  title: string

  /** Picture Links */
  pictureLinks: IPictureLink[]
}

export interface IPictureLinkGroup extends Entry<IPictureLinkGroupFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'pictureLinkGroup'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IPostFields {
  /** Title */
  title: string

  /** Slug */
  slug: string

  /** Body */
  body: Document

  /** Banner Image */
  bannerImage?: Asset | undefined

  /** Excerpt */
  excerpt?: string | undefined
}

/** A blog post */

export interface IPost extends Entry<IPostFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'post'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ISeriesFields {
  /** Title */
  title: string

  /** Slug */
  slug: string

  /** Items */
  items: Entry<{ [fieldId: string]: unknown }>[]
}

/** A collection of content in a particular order (e.g. a navigation menu, or a series of blog posts) */

export interface ISeries extends Entry<ISeriesFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'series'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ISnippetFields {
  /** Title */
  title: string

  /** Body */
  body: Document
}

/** A reuseable snippet of content to embed  */

export interface ISnippet extends Entry<ISnippetFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'snippet'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IYoutubeEmbedFields {
  /** Title */
  title: string

  /** Video URL */
  url: string
}

export interface IYoutubeEmbed extends Entry<IYoutubeEmbedFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'youtubeEmbed'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE =
  | 'button'
  | 'columnList'
  | 'contactForm'
  | 'contentBlock'
  | 'gridContainer'
  | 'gridItem'
  | 'link'
  | 'page'
  | 'pictureLink'
  | 'pictureLinkGroup'
  | 'post'
  | 'series'
  | 'snippet'
  | 'youtubeEmbed'

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
